### ISSUE TITLE
Installation via pip does not install all necessary directories/files, e.g. ./app/classes, ./app/templates/

### ISSUE THREAD

**Issue by JustGitting** [caltechads/nginx-ldap-auth-service#3]
I've install the package via pip, but I found two problems.

When starting the service via supervisord, it would produce the following error:

```python
RuntimeError: Directory '/usr/local/lib/python3.11/dist-packages/nginx_ldap_auth/app/static' does not exist
```

```python
Traceback (most recent call last):
  File "/usr/local/bin/nginx-ldap-auth", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/nginx_ldap_auth/main.py", line 4, in main
    cli(obj={})
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/nginx_ldap_auth/cli/server.py", line 86, in start
    uvicorn.run("nginx_ldap_auth.app.main:app", **uvicorn_kwargs)
  File "/usr/local/lib/python3.11/dist-packages/uvicorn/main.py", line 579, in run
    server.run()
  File "/usr/local/lib/python3.11/dist-packages/uvicorn/server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.11/dist-packages/uvicorn/server.py", line 70, in serve
    await self._serve(sockets)
  File "/usr/local/lib/python3.11/dist-packages/uvicorn/server.py", line 77, in _serve
    config.load()
  File "/usr/local/lib/python3.11/dist-packages/uvicorn/config.py", line 435, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.11/dist-packages/nginx_ldap_auth/app/main.py", line 91, in <module>
    app.mount("/auth/static", StaticFiles(directory=str(static_dir)), name="static")
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/starlette/staticfiles.py", line 56, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory '/usr/local/lib/python3.11/dist-packages/nginx_ldap_auth/app/static' does not exist
```

I fixed this by manually creating the `static` directory.

$ sudo mkdir /usr/local/lib/python3.11/dist-packages/nginx_ldap_auth/app/static

This fixed the runtime error and the nginx-ldap-auth service would start normally. However, when visiting the webpage that uses the LDAP authentication, it produced a 500 error:

```html
500 Server Error
TemplateNotFound: 'login.html' not found in search path: '/usr/local/lib/python3.11/dist-packages/nginx_ldap_auth/app/templates'
```

A list of installed files from the package is given below and `app/templates` is missing:

```python
$ sudo python3.11 -m pip show -f nginx-ldap-auth-service
Name: nginx_ldap_auth_service
Version: 2.1.2
Summary: A FastAPI app that authenticates users via LDAP and sets a cookie for nginx
Home-page:
Author:
Author-email: Caltech IMSS ADS <imss-ads-staff@caltech.edu>
License:
Location: /usr/local/lib/python3.11/dist-packages
Requires: aiodogstatsd, bonsai, click, fastapi, fastapi-csrf-protect, httptools, jinja2, pydantic, pydantic-settings, python-dotenv, python-multipart, sentry-sdk, starsessions, structlog, tabulate, uvicorn, watchfiles
Required-by:
Files:
  ../../../bin/nginx-ldap-auth
  build/lib/build/lib/build/lib/nginx_ldap_auth/__init__.py
  build/lib/build/lib/build/lib/nginx_ldap_auth/__pycache__/__init__.cpython-311.pyc
  build/lib/build/lib/build/lib/nginx_ldap_auth/__pycache__/ldap.cpython-311.pyc
  build/lib/build/lib/build/lib/nginx_ldap_auth/__pycache__/logging.cpython-311.pyc
  build/lib/build/lib/build/lib/nginx_ldap_auth/__pycache__/main.cpython-311.pyc
  build/lib/build/lib/build/lib/nginx_ldap_auth/__pycache__/settings.cpython-311.pyc
  build/lib/build/lib/build/lib/nginx_ldap_auth/__pycache__/types.cpython-311.pyc
  build/lib/build/lib/build/lib/nginx_ldap_auth/app/__init__.py
  build/lib/build/lib/build/lib/nginx_ldap_auth/app/__pycache__/__init__.cpython-311.pyc
  build/lib/build/lib/build/lib/nginx_ldap_auth/app/__pycache__/forms.cpython-311.pyc
  build/lib/build/lib/build/lib/nginx_ldap_auth/app/__pycache__/main.cpython-311.pyc
  build/lib/build/lib/build/lib/nginx_ldap_auth/app/__pycache__/middleware.cpython-311.pyc
  build/lib/build/lib/build/lib/nginx_ldap_auth/app/__pycache__/models.cpython-311.pyc
  build/lib/build/lib/build/lib/nginx_ldap_auth/app/forms.py
  build/lib/build/lib/build/lib/nginx_ldap_auth/app/main.py
  build/lib/build/lib/build/lib/nginx_ldap_auth/app/middleware.py
  build/lib/build/lib/build/lib/nginx_ldap_auth/app/models.py
  build/lib/build/lib/build/lib/nginx_ldap_auth/cli/__init__.py
  build/lib/build/lib/build/lib/nginx_ldap_auth/cli/__pycache__/__init__.cpython-311.pyc
  build/lib/build/lib/build/lib/nginx_ldap_auth/cli/__pycache__/cli.cpython-311.pyc
  build/lib/build/lib/build/lib/nginx_ldap_auth/cli/__pycache__/server.cpython-311.pyc
  build/lib/build/lib/build/lib/nginx_ldap_auth/cli/cli.py
  build/lib/build/lib/build/lib/nginx_ldap_auth/cli/server.py
  build/lib/build/lib/build/lib/nginx_ldap_auth/ldap.py
  build/lib/build/lib/build/lib/nginx_ldap_auth/logging.py
  build/lib/build/lib/build/lib/nginx_ldap_auth/main.py
  build/lib/build/lib/build/lib/nginx_ldap_auth/settings.py
  build/lib/build/lib/build/lib/nginx_ldap_auth/types.py
  build/lib/build/lib/doc/source/__pycache__/conf.cpython-311.pyc
  build/lib/build/lib/doc/source/conf.py
  build/lib/build/lib/nginx_ldap_auth/__init__.py
  build/lib/build/lib/nginx_ldap_auth/__pycache__/__init__.cpython-311.pyc
  build/lib/build/lib/nginx_ldap_auth/__pycache__/ldap.cpython-311.pyc
  build/lib/build/lib/nginx_ldap_auth/__pycache__/logging.cpython-311.pyc
  build/lib/build/lib/nginx_ldap_auth/__pycache__/main.cpython-311.pyc
  build/lib/build/lib/nginx_ldap_auth/__pycache__/settings.cpython-311.pyc
  build/lib/build/lib/nginx_ldap_auth/__pycache__/types.cpython-311.pyc
  build/lib/build/lib/nginx_ldap_auth/app/__init__.py
  build/lib/build/lib/nginx_ldap_auth/app/__pycache__/__init__.cpython-311.pyc
  build/lib/build/lib/nginx_ldap_auth/app/__pycache__/forms.cpython-311.pyc
  build/lib/build/lib/nginx_ldap_auth/app/__pycache__/main.cpython-311.pyc
  build/lib/build/lib/nginx_ldap_auth/app/__pycache__/middleware.cpython-311.pyc
  build/lib/build/lib/nginx_ldap_auth/app/__pycache__/models.cpython-311.pyc
  build/lib/build/lib/nginx_ldap_auth/app/forms.py
  build/lib/build/lib/nginx_ldap_auth/app/main.py
  build/lib/build/lib/nginx_ldap_auth/app/middleware.py
  build/lib/build/lib/nginx_ldap_auth/app/models.py
  build/lib/build/lib/nginx_ldap_auth/cli/__init__.py
  build/lib/build/lib/nginx_ldap_auth/cli/__pycache__/__init__.cpython-311.pyc
  build/lib/build/lib/nginx_ldap_auth/cli/__pycache__/cli.cpython-311.pyc
  build/lib/build/lib/nginx_ldap_auth/cli/__pycache__/server.cpython-311.pyc
  build/lib/build/lib/nginx_ldap_auth/cli/cli.py
  build/lib/build/lib/nginx_ldap_auth/cli/server.py
  build/lib/build/lib/nginx_ldap_auth/ldap.py
  build/lib/build/lib/nginx_ldap_auth/logging.py
  build/lib/build/lib/nginx_ldap_auth/main.py
  build/lib/build/lib/nginx_ldap_auth/py.typed
  build/lib/build/lib/nginx_ldap_auth/settings.py
  build/lib/build/lib/nginx_ldap_auth/types.py
  build/lib/doc/source/__pycache__/conf.cpython-311.pyc
  build/lib/doc/source/conf.py
  build/lib/nginx_ldap_auth/__init__.py
  build/lib/nginx_ldap_auth/__pycache__/__init__.cpython-311.pyc
  build/lib/nginx_ldap_auth/__pycache__/ldap.cpython-311.pyc
  build/lib/nginx_ldap_auth/__pycache__/logging.cpython-311.pyc
  build/lib/nginx_ldap_auth/__pycache__/main.cpython-311.pyc
  build/lib/nginx_ldap_auth/__pycache__/settings.cpython-311.pyc
  build/lib/nginx_ldap_auth/__pycache__/types.cpython-311.pyc
  build/lib/nginx_ldap_auth/app/__init__.py
  build/lib/nginx_ldap_auth/app/__pycache__/__init__.cpython-311.pyc
  build/lib/nginx_ldap_auth/app/__pycache__/forms.cpython-311.pyc
  build/lib/nginx_ldap_auth/app/__pycache__/main.cpython-311.pyc
  build/lib/nginx_ldap_auth/app/__pycache__/middleware.cpython-311.pyc
  build/lib/nginx_ldap_auth/app/__pycache__/models.cpython-311.pyc
  build/lib/nginx_ldap_auth/app/forms.py
  build/lib/nginx_ldap_auth/app/main.py
  build/lib/nginx_ldap_auth/app/middleware.py
  build/lib/nginx_ldap_auth/app/models.py
  build/lib/nginx_ldap_auth/cli/__init__.py
  build/lib/nginx_ldap_auth/cli/__pycache__/__init__.cpython-311.pyc
  build/lib/nginx_ldap_auth/cli/__pycache__/cli.cpython-311.pyc
  build/lib/nginx_ldap_auth/cli/__pycache__/server.cpython-311.pyc
  build/lib/nginx_ldap_auth/cli/cli.py
  build/lib/nginx_ldap_auth/cli/server.py
  build/lib/nginx_ldap_auth/ldap.py
  build/lib/nginx_ldap_auth/logging.py
  build/lib/nginx_ldap_auth/main.py
  build/lib/nginx_ldap_auth/py.typed
  build/lib/nginx_ldap_auth/settings.py
  build/lib/nginx_ldap_auth/types.py
  doc/source/__pycache__/conf.cpython-311.pyc
  doc/source/conf.py
  etc/environment.txt
  etc/nginx/certs/localhost.crt
  etc/nginx/certs/localhost.key
  etc/nginx/nginx.conf
  nginx_ldap_auth/__init__.py
  nginx_ldap_auth/__pycache__/__init__.cpython-311.pyc
  nginx_ldap_auth/__pycache__/ldap.cpython-311.pyc
  nginx_ldap_auth/__pycache__/logging.cpython-311.pyc
  nginx_ldap_auth/__pycache__/main.cpython-311.pyc
  nginx_ldap_auth/__pycache__/settings.cpython-311.pyc
  nginx_ldap_auth/__pycache__/types.cpython-311.pyc
  nginx_ldap_auth/app/__init__.py
  nginx_ldap_auth/app/__pycache__/__init__.cpython-311.pyc
  nginx_ldap_auth/app/__pycache__/forms.cpython-311.pyc
  nginx_ldap_auth/app/__pycache__/main.cpython-311.pyc
  nginx_ldap_auth/app/__pycache__/middleware.cpython-311.pyc
  nginx_ldap_auth/app/__pycache__/models.cpython-311.pyc
  nginx_ldap_auth/app/forms.py
  nginx_ldap_auth/app/main.py
  nginx_ldap_auth/app/middleware.py
  nginx_ldap_auth/app/models.py
  nginx_ldap_auth/cli/__init__.py
  nginx_ldap_auth/cli/__pycache__/__init__.cpython-311.pyc
  nginx_ldap_auth/cli/__pycache__/cli.cpython-311.pyc
  nginx_ldap_auth/cli/__pycache__/server.cpython-311.pyc
  nginx_ldap_auth/cli/cli.py
  nginx_ldap_auth/cli/server.py
  nginx_ldap_auth/ldap.py
  nginx_ldap_auth/logging.py
  nginx_ldap_auth/main.py
  nginx_ldap_auth/py.typed
  nginx_ldap_auth/settings.py
  nginx_ldap_auth/types.py
  nginx_ldap_auth_service-2.1.2.dist-info/INSTALLER
  nginx_ldap_auth_service-2.1.2.dist-info/LICENSE.txt
  nginx_ldap_auth_service-2.1.2.dist-info/METADATA
  nginx_ldap_auth_service-2.1.2.dist-info/RECORD
  nginx_ldap_auth_service-2.1.2.dist-info/REQUESTED
  nginx_ldap_auth_service-2.1.2.dist-info/WHEEL
  nginx_ldap_auth_service-2.1.2.dist-info/entry_points.txt
  nginx_ldap_auth_service-2.1.2.dist-info/top_level.txt
```

I also tried installing the git version, but it's the same problem of missing folders/files.

```python
$ sudo python3.11 -m pip uninstall nginx-ldap-auth-service
$ sudo pip install git+https://github.com/caltechads/nginx-ldap-auth-service.git
```

```python
$ sudo python3.11 -m pip show -f nginx-ldap-auth-service
Name: nginx_ldap_auth_service
Version: 2.1.2
Summary: A FastAPI app that authenticates users via LDAP and sets a cookie for nginx
Home-page:
Author:
Author-email: Caltech IMSS ADS <imss-ads-staff@caltech.edu>
License:
Location: /usr/local/lib/python3.11/dist-packages
Requires: aiodogstatsd, bonsai, click, fastapi, fastapi-csrf-protect, httptools, jinja2, pydantic, pydantic-settings, python-dotenv, python-multipart, sentry-sdk, starsessions, structlog, tabulate, uvicorn, watchfiles
Required-by:
Files:
  ../../../bin/nginx-ldap-auth
  doc/source/__pycache__/conf.cpython-311.pyc
  doc/source/conf.py
  etc/environment.txt
  etc/nginx/certs/localhost.crt
  etc/nginx/certs/localhost.key
  etc/nginx/nginx.conf
  nginx_ldap_auth/__init__.py
  nginx_ldap_auth/__pycache__/__init__.cpython-311.pyc
  nginx_ldap_auth/__pycache__/ldap.cpython-311.pyc
  nginx_ldap_auth/__pycache__/logging.cpython-311.pyc
  nginx_ldap_auth/__pycache__/main.cpython-311.pyc
  nginx_ldap_auth/__pycache__/settings.cpython-311.pyc
  nginx_ldap_auth/__pycache__/types.cpython-311.pyc
  nginx_ldap_auth/app/__init__.py
  nginx_ldap_auth/app/__pycache__/__init__.cpython-311.pyc
  nginx_ldap_auth/app/__pycache__/forms.cpython-311.pyc
  nginx_ldap_auth/app/__pycache__/main.cpython-311.pyc
  nginx_ldap_auth/app/__pycache__/middleware.cpython-311.pyc
  nginx_ldap_auth/app/__pycache__/models.cpython-311.pyc
  nginx_ldap_auth/app/forms.py
  nginx_ldap_auth/app/main.py
  nginx_ldap_auth/app/middleware.py
  nginx_ldap_auth/app/models.py
  nginx_ldap_auth/cli/__init__.py
  nginx_ldap_auth/cli/__pycache__/__init__.cpython-311.pyc
  nginx_ldap_auth/cli/__pycache__/cli.cpython-311.pyc
  nginx_ldap_auth/cli/__pycache__/server.cpython-311.pyc
  nginx_ldap_auth/cli/cli.py
  nginx_ldap_auth/cli/server.py
  nginx_ldap_auth/ldap.py
  nginx_ldap_auth/logging.py
  nginx_ldap_auth/main.py
  nginx_ldap_auth/py.typed
  nginx_ldap_auth/settings.py
  nginx_ldap_auth/types.py
  nginx_ldap_auth_service-2.1.2.dist-info/INSTALLER
  nginx_ldap_auth_service-2.1.2.dist-info/LICENSE.txt
  nginx_ldap_auth_service-2.1.2.dist-info/METADATA
  nginx_ldap_auth_service-2.1.2.dist-info/RECORD
  nginx_ldap_auth_service-2.1.2.dist-info/REQUESTED
  nginx_ldap_auth_service-2.1.2.dist-info/WHEEL
  nginx_ldap_auth_service-2.1.2.dist-info/direct_url.json
  nginx_ldap_auth_service-2.1.2.dist-info/entry_points.txt
  nginx_ldap_auth_service-2.1.2.dist-info/top_level.txt
```

Checking this repo shows both `./app/static` and `./app/templates` to be present. Is there are trick to installing the package with the extra directories/files?

**Comment by cmalek** [comment]
Thanks for the research!  I changed from `setup.py` to `pyproject.toml` last release and obviously I lost my package data (the non python files) in the distribution.  I didn't notice since I only use the docker version.

I'll fix and release a new version.

**Comment by cmalek** [comment]
I've released a fix for this in v2.1.3.  Could you give it a try?

**Comment by DanRimal24** [comment]
Hello Chris,

Looks like issue persist, i just install pip package, and cannot run even "version". I am not sure if it is the same error like before:

Thanks for all your effort.

`(ldap-auth) root@do2-ctn-nginx:/opt# pip list | grep nginx
nginx_ldap_auth_service 2.1.4`

`(ldap-auth) root@do2-ctn-nginx:/opt# ./ldap-auth/bin/nginx-ldap-auth -v
Traceback (most recent call last):
  File "/opt/./ldap-auth/bin/nginx-ldap-auth", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/ldap-auth/lib/python3.11/site-packages/nginx_ldap_auth/main.py", line 2, in main
    from .cli import cli
  File "/opt/ldap-auth/lib/python3.11/site-packages/nginx_ldap_auth/cli/__init__.py", line 2, in <module>
    from .server import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ldap-auth/lib/python3.11/site-packages/nginx_ldap_auth/cli/server.py", line 10, in <module>
    settings = Settings()
               ^^^^^^^^^^
  File "/opt/ldap-auth/lib/python3.11/site-packages/pydantic_settings/main.py", line 176, in __init__
    super().__init__(
  File "/opt/ldap-auth/lib/python3.11/site-packages/pydantic/main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 5 validation errors for Settings
secret_key
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
ldap_uri
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
ldap_binddn
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
ldap_password
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
ldap_basedn
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing`

**Comment by DanRimal24** [comment]
Mea culpa, daemon cannot run without cfg, even for "-v". Looks good now.

**Comment by cmalek** [comment]
Glad you figured it out!  I was just about to say that.
